// Code generated by netbadb-codegen; DO NOT EDIT.
// Source: sdk/go/testschema/schema.json
// Regenerate: cargo run -p netbadb-codegen -- go --schema sdk/go/testschema/schema.json --package testschema --output sdk/go/testschema/netbadb_generated.go

package testschema

import (
	"context"

	netbadb "github.com/sskycn/netbadb/sdk/go"
)

type UserId int64

type Queryer interface {
	Query(context.Context, string) (*netbadb.Rows, error)
}

const UsersTableId netbadb.TableID = 1
const UsersIdColumnId netbadb.ColumnID = 1
const UsersNameColumnId netbadb.ColumnID = 2

func UsersIdentity() netbadb.TableIdentity {
	return netbadb.TableIdentity{TableID: UsersTableId, Fingerprint: netbadb.SchemaFingerprint{0x28, 0x9a, 0x19, 0x22, 0x1d, 0x61, 0x95, 0x99, 0xd3, 0x07, 0x73, 0xc0, 0x74, 0xf8, 0xad, 0x9a, 0x5e, 0x75, 0xdf, 0x08, 0x0f, 0x1c, 0x5a, 0xed, 0xf3, 0x37, 0x94, 0x4a, 0xd9, 0x1f, 0x39, 0xae}}
}

type UsersRow struct {
	Id   UserId
	Name netbadb.Nullable[string]
}

func ValidateUsersColumns(columns []netbadb.ResultColumn) error {
	if len(columns) != 2 {
		return &netbadb.ResultShapeError{Reason: "users: expected 2 columns"}
	}
	if columns[0].Name != "id" || columns[0].Type.Physical != netbadb.PhysicalTypeInt64 || columns[0].Type.Named != true || columns[0].Type.Name != "UserId" || columns[0].Nullable != false {
		return &netbadb.ResultShapeError{Reason: "users: column 1 does not match the canonical full-row shape"}
	}
	if columns[1].Name != "name" || columns[1].Type.Physical != netbadb.PhysicalTypeText || columns[1].Type.Named != false || columns[1].Type.Name != "" || columns[1].Nullable != true {
		return &netbadb.ResultShapeError{Reason: "users: column 2 does not match the canonical full-row shape"}
	}
	return nil
}

func DecodeUsersRow(values []netbadb.Value) (UsersRow, error) {
	var row UsersRow
	if len(values) != 2 {
		return row, &netbadb.ResultShapeError{Reason: "users: expected 2 row values"}
	}
	raw, ok := values[0].Int64()
	if !ok {
		return row, &netbadb.ResultShapeError{Reason: "users.id is NULL or has the wrong physical value"}
	}
	row.Id = UserId(raw)
	if !values[1].IsNull() {
		raw, ok := values[1].Text()
		if !ok {
			return row, &netbadb.ResultShapeError{Reason: "users.name has the wrong physical value"}
		}
		row.Name = netbadb.Some(raw)
	}
	return row, nil
}

type UsersRows struct {
	rows    *netbadb.Rows
	current UsersRow
	err     error
}

func (rows *UsersRows) Next() bool {
	if rows == nil || rows.err != nil || !rows.rows.Next() {
		return false
	}
	row, err := DecodeUsersRow(rows.rows.Values())
	if err != nil {
		if closeErr := rows.rows.Close(); closeErr != nil {
			rows.err = closeErr
		} else {
			rows.err = err
		}
		return false
	}
	rows.current = row
	return true
}

func (rows *UsersRows) Row() UsersRow {
	if rows == nil {
		return UsersRow{}
	}
	return rows.current
}

func (rows *UsersRows) Err() error {
	if rows == nil {
		return nil
	}
	if rows.err != nil {
		return rows.err
	}
	return rows.rows.Err()
}

func (rows *UsersRows) Close() error {
	if rows == nil {
		return nil
	}
	if rows.err != nil {
		return rows.err
	}
	return rows.rows.Close()
}

func QueryUsers(ctx context.Context, queryer Queryer, sql string) (*UsersRows, error) {
	rows, err := queryer.Query(ctx, sql)
	if err != nil {
		return nil, err
	}
	if err := ValidateUsersColumns(rows.Columns()); err != nil {
		if closeErr := rows.Close(); closeErr != nil {
			return nil, closeErr
		}
		return nil, err
	}
	return &UsersRows{rows: rows}, nil
}

func RequiredSchemas() []netbadb.TableIdentity {
	return []netbadb.TableIdentity{
		UsersIdentity(),
	}
}

func Dial(ctx context.Context, config netbadb.Config) (*netbadb.Client, error) {
	required := make([]netbadb.TableIdentity, 0, len(config.RequiredSchemas)+1)
	required = append(required, config.RequiredSchemas...)
	required = append(required, RequiredSchemas()...)
	config.RequiredSchemas = required
	return netbadb.Dial(ctx, config)
}
