[package]
name = "netbadb-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
netbadb-schema = { path = "../netbadb-schema" }
netbadb-types = { path = "../netbadb-types" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true

