[package]
name = "netbadb-tooling"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
netbadb-compiler = { path = "../netbadb-compiler" }
netbadb-hir = { path = "../netbadb-hir" }
netbadb-parser = { path = "../netbadb-parser" }
netbadb-schema = { path = "../netbadb-schema" }

[dev-dependencies]
netbadb-types = { path = "../netbadb-types" }

[lints]
workspace = true
